# Generated by Django 4.2.1 on 2023-06-15 19:12

from django.db import migrations, models
import first_app.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[first_app.validator.validator_name])),
                ('surname', models.CharField(max_length=50, validators=[first_app.validator.validator_surname])),
                ('age', models.IntegerField(validators=[first_app.validator.validator_age])),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=30)),
                ('work_status', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=60)),
                ('favorite_genre', models.CharField(max_length=80)),
                ('visiting_time', models.TimeField()),
                ('favorite_platform', models.CharField(choices=[('PC', 'PC'), ('XBOX', 'XBOX'), ('Playstation', 'Playstation')], max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('opinion', models.TextField()),
            ],
        ),
    ]
