# Generated by Django 4.2.1 on 2023-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='work_status',
            field=models.CharField(max_length=60),
        ),
    ]
